## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file civil.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_66 = Integer(66); _sage_const_41 = Integer(41); _sage_const_18 = Integer(18); _sage_const_44 = Integer(44); _sage_const_63 = Integer(63); _sage_const_60 = Integer(60); _sage_const_47 = Integer(47); _sage_const_35 = Integer(35); _sage_const_87 = Integer(87); _sage_const_81 = Integer(81); _sage_const_69 = Integer(69); _sage_const_13 = Integer(13); _sage_const_38 = Integer(38); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_57 = Integer(57); _sage_const_30 = Integer(30); _sage_const_55 = Integer(55); _sage_const_32 = Integer(32); _sage_const_53 = Integer(53); _sage_const_50 = Integer(50); _sage_const_75 = Integer(75); _sage_const_12 = Integer(12); _sage_const_92 = Integer(92); _sage_const_72 = Integer(72); _sage_const_97 = Integer(97)## This file (civil.sagetex.sage) was *autogenerated* from civil.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('civil', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 load('input.sage')
 load('main.sage')
 
 
except:
 _st_.goboom(_sage_const_30 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(Number_of_storeys))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.inline(_sage_const_1 , latex(Stiffness_matrix))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.inline(_sage_const_2 , latex(Mass))
except:
 _st_.goboom(_sage_const_38 )
try:
 _st_.inline(_sage_const_3 , latex(matrix(Omega_square).n(digits=_sage_const_6 )))
except:
 _st_.goboom(_sage_const_41 )
try:
 _st_.inline(_sage_const_4 , latex(Time_period.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.inline(_sage_const_5 , latex(Frequency))
except:
 _st_.goboom(_sage_const_47 )
try:
 _st_.inline(_sage_const_6 , latex(XX))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.inline(_sage_const_7 , latex(matrix(Level_floor).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=q)
except:
 _st_.goboom(_sage_const_55 )
try:
 _st_.inline(_sage_const_8 , latex(matrix(Modal_participation_factor).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.inline(_sage_const_9 , latex(matrix(Modal_mass).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_60 )
try:
 _st_.inline(_sage_const_10 , latex(matrix(Modal_contribution)))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.inline(_sage_const_11 , latex(Sa_by_g.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.inline(_sage_const_12 , latex(A_h.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_69 )
try:
 _st_.inline(_sage_const_13 , latex(Design_lateral_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.inline(_sage_const_14 , latex(Peak_shear_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_75 )
try:
 _st_.inline(_sage_const_15 , latex(Storey_shear_force[:,_sage_const_1 ].n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_81 )
try:
 _st_.inline(_sage_const_16 , latex(Storey_shear_force[:,_sage_const_2 ].n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.inline(_sage_const_17 , latex(Lateral_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.inline(_sage_const_18 , latex(Force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_97 )
_st_.endofdoc()
