## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file civil.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_33 = Integer(33); _sage_const_67 = Integer(67); _sage_const_42 = Integer(42); _sage_const_45 = Integer(45); _sage_const_61 = Integer(61); _sage_const_48 = Integer(48); _sage_const_85 = Integer(85); _sage_const_36 = Integer(36); _sage_const_64 = Integer(64); _sage_const_39 = Integer(39); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_58 = Integer(58); _sage_const_31 = Integer(31); _sage_const_55 = Integer(55); _sage_const_52 = Integer(52); _sage_const_50 = Integer(50); _sage_const_13 = Integer(13); _sage_const_70 = Integer(70); _sage_const_73 = Integer(73); _sage_const_90 = Integer(90); _sage_const_79 = Integer(79); _sage_const_95 = Integer(95); _sage_const_14 = Integer(14)## This file (civil.sagetex.sage) was *autogenerated* from civil.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('civil', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 load('input.sage')
 load('main.sage')
 
 
except:
 _st_.goboom(_sage_const_31 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(Number_of_storeys))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.inline(_sage_const_1 , latex(Stiffness_matrix))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.inline(_sage_const_2 , latex(Mass))
except:
 _st_.goboom(_sage_const_39 )
try:
 _st_.inline(_sage_const_3 , latex(matrix(Omega_square).n(digits=_sage_const_6 )))
except:
 _st_.goboom(_sage_const_42 )
try:
 _st_.inline(_sage_const_4 , latex(Time_period.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_45 )
try:
 _st_.inline(_sage_const_5 , latex(Frequency))
except:
 _st_.goboom(_sage_const_48 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=q)
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.inline(_sage_const_6 , latex(matrix(Level_floor).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.inline(_sage_const_7 , latex(matrix(Modal_participation_factor).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_55 )
try:
 _st_.inline(_sage_const_8 , latex(matrix(Modal_mass).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_58 )
try:
 _st_.inline(_sage_const_9 , latex(matrix(Modal_contribution)))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.inline(_sage_const_10 , latex(Sa_by_g.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_64 )
try:
 _st_.inline(_sage_const_11 , latex(A_h.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_67 )
try:
 _st_.inline(_sage_const_12 , latex(Design_lateral_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_70 )
try:
 _st_.inline(_sage_const_13 , latex(Peak_shear_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_73 )
try:
 _st_.inline(_sage_const_14 , latex(Storey_shear_force[:,_sage_const_1 ].n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_79 )
try:
 _st_.inline(_sage_const_15 , latex(Storey_shear_force[:,_sage_const_2 ].n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_85 )
try:
 _st_.inline(_sage_const_16 , latex(Lateral_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.inline(_sage_const_17 , latex(Force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_95 )
_st_.endofdoc()
