# This file was *autogenerated* from the file input.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9p81 = RealNumber('9.81'); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_0p24 = RealNumber('0.24'); _sage_const_1000 = Integer(1000); _sage_const_600 = Integer(600); _sage_const_800 = Integer(800)
Number_of_storeys=_sage_const_4 
Soil_type=_sage_const_1 
Importance_factor=_sage_const_1 
Response_reduction_factor=_sage_const_5 
Zone_factor=_sage_const_0p24 
Gravity_acceleration=_sage_const_9p81 
Modes_considered=_sage_const_4 
Mass=matrix([[_sage_const_8 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0  ,_sage_const_8  ,_sage_const_0 , _sage_const_0 ],[_sage_const_0 , _sage_const_0 , _sage_const_4 , _sage_const_0 ],[_sage_const_0 ,_sage_const_0  ,_sage_const_0  ,_sage_const_4 ]])
Height_storey=matrix([[_sage_const_4 ],[_sage_const_4 ],[_sage_const_4 ],[_sage_const_4 ]])
Stiffness_storey=matrix([[_sage_const_1000 ],[_sage_const_800 ],[_sage_const_600 ],[_sage_const_600 ]])

