## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file civil.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_15 = Integer(15); _sage_const_23 = Integer(23); _sage_const_25 = Integer(25); _sage_const_40 = Integer(40); _sage_const_42 = Integer(42); _sage_const_65 = Integer(65); _sage_const_44 = Integer(44); _sage_const_62 = Integer(62); _sage_const_47 = Integer(47); _sage_const_87 = Integer(87); _sage_const_82 = Integer(82); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_59 = Integer(59); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_56 = Integer(56); _sage_const_53 = Integer(53); _sage_const_34 = Integer(34); _sage_const_37 = Integer(37); _sage_const_50 = Integer(50); _sage_const_77 = Integer(77); _sage_const_71 = Integer(71)## This file (civil.sagetex.sage) was *autogenerated* from civil.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('civil', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
 load('input.sage')
 load('main.sage')
 
 
except:
 _st_.goboom(_sage_const_23 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , latex(Number_of_storeys))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.inline(_sage_const_1 , latex(Stiffness_matrix))
except:
 _st_.goboom(_sage_const_28 )
try:
 _st_.inline(_sage_const_2 , latex(Mass))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.inline(_sage_const_3 , latex(matrix(Omega_square).n(digits=_sage_const_6 )))
except:
 _st_.goboom(_sage_const_34 )
try:
 _st_.inline(_sage_const_4 , latex(Time_period.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_37 )
try:
 _st_.inline(_sage_const_5 , latex(Omega.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=Graph)
except:
 _st_.goboom(_sage_const_42 )
try:
 _st_.inline(_sage_const_6 , latex(matrix(Level_floor).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.inline(_sage_const_7 , latex(matrix(Modal_participation_factor).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_47 )
try:
 _st_.inline(_sage_const_8 , latex(matrix(Modal_mass).n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.inline(_sage_const_9 , latex(matrix(Modal_contribution)))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.inline(_sage_const_10 , latex(Sa_by_g.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_56 )
try:
 _st_.inline(_sage_const_11 , latex(A_h.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.inline(_sage_const_12 , latex(Design_lateral_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.inline(_sage_const_13 , latex(Peak_shear_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_65 )
try:
 _st_.inline(_sage_const_14 , latex(Storey_shear_force[:,_sage_const_1 ].n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_71 )
try:
 _st_.inline(_sage_const_15 , latex(Storey_shear_force[:,_sage_const_2 ].n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.inline(_sage_const_16 , latex(Lateral_force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_82 )
try:
 _st_.inline(_sage_const_17 , latex(Force.n(digits=_sage_const_4 )))
except:
 _st_.goboom(_sage_const_87 )
_st_.endofdoc()
