# This file was *autogenerated* from the file sagemath/input.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_44 = Integer(44); _sage_const_4 = Integer(4); _sage_const_1p5 = RealNumber('1.5'); _sage_const_p1 = RealNumber('.1'); _sage_const_9p8 = RealNumber('9.8'); _sage_const_23 = Integer(23); _sage_const_32 = Integer(32); _sage_const_34 = Integer(34)
Soil_type=_sage_const_1 
Importance_factor=_sage_const_1p5 
Number_of_storeys=_sage_const_4 
Gravity_acceleration=_sage_const_9p8 
Modes_considered=_sage_const_4 
Response_reduction_factor=_sage_const_1p5 
Zone_factor=_sage_const_p1 
mass=matrix([[_sage_const_23 ],[_sage_const_23 ],[_sage_const_32 ],[_sage_const_34 ]])
Height_storey=matrix([[_sage_const_44 ],[_sage_const_44 ],[_sage_const_23 ],[_sage_const_34 ],])
Stiffness_storey=matrix([[_sage_const_34 ],[_sage_const_34 ],[_sage_const_23 ],[_sage_const_34 ],])
